spring:
  datasource:
    url: jdbc:tc:postgresql:15.5:///integration-tests-db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: "sa"
    password: "sa"
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: public